// AUTO-GENERATED by VAE — do not edit
// Source: diode_simple
#include <cmath>
#include <cstring>

// Limiting exponential — prevents overflow
static inline double vae_limexp(double x) {
    if (x > 80.0) return exp(80.0) * (1.0 + x - 80.0);
    if (x < -80.0) return exp(-80.0);
    return exp(x);
}

// $limit stub — limiting handled by device wrapper
struct VaeState;
static inline double vae_limit(VaeState*, double v, ...) { return v; }

struct VaeState {
    double* V;            // node voltages (caller-allocated)
    double* params;       // model/instance parameters (caller-allocated)
    double temperature;   // device temperature (K)
    double Vt;            // thermal voltage kT/q
    double dt;            // timestep
    double time;          // current time
};

#ifndef CONSTroot2
#define CONSTroot2 1.41421356237309504880
#endif
#ifndef X_K
#define X_K 1.3806226e23
#endif
#ifndef CONSTboltz
#define CONSTboltz 1.3806226e-23
#endif
#ifndef CONSTq
#define CONSTq 1.602176634e-19
#endif

extern "C" {

void vae_eval(VaeState* s, double* F, double* Q) {
    double V_a_ci = s->V[0] - s->V[2];
    double V_ci_c = s->V[2] - s->V[1];

    memset(F, 0, 2 * sizeof(double));
    memset(Q, 0, 2 * sizeof(double));

    double vcrit = s->Vt * log ( s->Vt / ( CONSTroot2 * s->params[0] ) );
    double Vd = vae_limit(s, (s->V[2] - s->V[0]) , "pnjlim" , s->Vt , vcrit );
    double exparg = Vd / 26e-3;
    double Id = s->params[0] * ( vae_limexp ( exparg ) -1 );
    double Qp = s->params[1] * Vd;
    F[0] += Id;
    Q[0] += Qp;
    if (s->params[2] > 0) {
    F[1] += (s->V[2] - s->V[1]) / s->params[2];
    } else {
    // V(ci,c) <+ 0.0
    F[1] += 0.0 - V_ci_c;
    }
}

void vae_jacobian(VaeState* s, double* dFdV, double* dQdV) {
    // dFdV[row * 3 + col], dQdV[row * 3 + col]
    double V_a_ci = s->V[0] - s->V[2];
    double V_ci_c = s->V[2] - s->V[1];
    memset(dFdV, 0, 2 * 3 * sizeof(double));
    memset(dQdV, 0, 2 * 3 * sizeof(double));

    double vcrit = s->Vt * log ( s->Vt / ( CONSTroot2 * s->params[0] ) );
    double Vd = vae_limit(s, (s->V[2] - s->V[0]) , "pnjlim" , s->Vt , vcrit );
    double exparg = Vd / 26e-3;
    double Id = s->params[0] * ( vae_limexp ( exparg ) -1 );
    double Qp = s->params[1] * Vd;
    dFdV[0 * 3 + 0] += -38.46153846153846*s->params[0]*exp(-38.46153846153846*s->V[0] + 38.46153846153846*s->V[2]);
    dFdV[0 * 3 + 2] += 38.46153846153846*s->params[0]*exp(-38.46153846153846*s->V[0] + 38.46153846153846*s->V[2]);
    dQdV[0 * 3 + 0] += -s->params[1];
    dQdV[0 * 3 + 2] += s->params[1];
    if (s->params[2] > 0) {
    dFdV[1 * 3 + 1] += -1/s->params[2];
    dFdV[1 * 3 + 2] += 1.0/s->params[2];
    } else {
    dFdV[1 * 3 + 1] += 1;
    dFdV[1 * 3 + 2] += -1;
    }
}

const char* vae_model_name() { return "diode_simple"; }
int vae_port_count() { return 2; }
int vae_internal_node_count() { return 1; }
int vae_branch_count() { return 2; }

const char* vae_port_name(int i) {
    static const char* names[] = {
        "a",
        "c",
        "ci",
    };
    return (i >= 0 && i < 3) ? names[i] : "";
}

void vae_branch_info(int i, int* node_p, int* node_n, int* is_vsrc) {
    if (i == 0) { *node_p = 0; *node_n = 2; *is_vsrc = 0; return; }
    if (i == 1) { *node_p = 2; *node_n = 1; *is_vsrc = 1; return; }
}

int vae_param_count() { return 4; }
const char* vae_param_name(int i) {
    static const char* names[] = {
        "Is",
        "Cp",
        "Rs",
        "Temp",
    };
    return (i >= 0 && i < 4) ? names[i] : "";
}
double vae_param_default(int i) {
    static const double defaults[] = {
        1e-5,
        1e-12,
        1,
        300,
    };
    return (i >= 0 && i < 4) ? defaults[i] : 0.0;
}

} // extern "C"
