// AUTO-GENERATED by VAE — do not edit
// Source: resistor
#include <cmath>
#include <cstring>

// Limiting exponential — prevents overflow
static inline double vae_limexp(double x) {
    if (x > 80.0) return exp(80.0) * (1.0 + x - 80.0);
    if (x < -80.0) return exp(-80.0);
    return exp(x);
}

// $limit stub — limiting handled by device wrapper
struct VaeState;
static inline double vae_limit(VaeState*, double v, ...) { return v; }

struct VaeState {
    double* V;            // node voltages (caller-allocated)
    double* params;       // model/instance parameters (caller-allocated)
    double temperature;   // device temperature (K)
    double Vt;            // thermal voltage kT/q
    double dt;            // timestep
    double time;          // current time
};

#ifndef CONSTroot2
#define CONSTroot2 1.41421356237309504880
#endif
#ifndef X_K
#define X_K 1.3806226e23
#endif
#ifndef CONSTboltz
#define CONSTboltz 1.3806226e-23
#endif
#ifndef CONSTq
#define CONSTq 1.602176634e-19
#endif

extern "C" {

void vae_eval(VaeState* s, double* F, double* Q) {
    double V_p_n = s->V[0] - s->V[1];

    memset(F, 0, 1 * sizeof(double));
    memset(Q, 0, 1 * sizeof(double));

    double tdevK = s->temperature;
    double conductance = 1.0 / s->params[0];
    double Ir = (s->V[0] - s->V[1]) * conductance;
    F[0] += Ir;
    F[0] += 0.0;
}

void vae_jacobian(VaeState* s, double* dFdV, double* dQdV) {
    // dFdV[row * 2 + col], dQdV[row * 2 + col]
    double V_p_n = s->V[0] - s->V[1];
    memset(dFdV, 0, 1 * 2 * sizeof(double));
    memset(dQdV, 0, 1 * 2 * sizeof(double));

    double tdevK = s->temperature;
    double conductance = 1.0 / s->params[0];
    double Ir = (s->V[0] - s->V[1]) * conductance;
    dFdV[0 * 2 + 0] += 1.0/s->params[0];
    dFdV[0 * 2 + 1] += -1.0/s->params[0];
}

const char* vae_model_name() { return "resistor"; }
int vae_port_count() { return 2; }
int vae_internal_node_count() { return 0; }
int vae_branch_count() { return 1; }

const char* vae_port_name(int i) {
    static const char* names[] = {
        "p",
        "n",
    };
    return (i >= 0 && i < 2) ? names[i] : "";
}

void vae_branch_info(int i, int* node_p, int* node_n, int* is_vsrc) {
    if (i == 0) { *node_p = 0; *node_n = 1; *is_vsrc = 0; return; }
}

int vae_param_count() { return 1; }
const char* vae_param_name(int i) {
    static const char* names[] = {
        "R",
    };
    return (i >= 0 && i < 1) ? names[i] : "";
}
double vae_param_default(int i) {
    static const double defaults[] = {
        1,
    };
    return (i >= 0 && i < 1) ? defaults[i] : 0.0;
}

} // extern "C"
