#!/usr/bin/env python3
"""
xyce_from_vhdl - Extract Xyce subcircuit from VHDL wrapper and
                 generate a complete cosim-ready Xyce deck with
                 YDAC/YADC PWL hooks at the boundary ports.

Reads VHDL files generated by xyce_to_vhdl.py, extracts the
xyce_subckt() payload, reconstructs the SPICE netlist, adds
DAC/ADC interface devices for each signal port, and generates
the boundary config for the NVC cosim driver.

Usage:
    xyce_from_vhdl.py <wrapper.vhd> [-o outdir] [--vdd 1.8] [--tstop 100ns]

Output:
    <name>.cir        - Complete Xyce netlist with PWL hooks
    <name>.boundary   - Boundary config for nvc --xyce-config

This is a Python elaboration step: slow is fine, user-tweakable is good.
"""

import argparse
import os
import re
import sys


def extract_spice_subckt_payload(vhdl_text):
    """Extract the spice_subckt() string payload from VHDL source.

    Handles multi-line VHDL string concatenation with &.
    Returns the reconstructed payload string, or None.
    """
    m = re.search(r'spice_subckt\s*\(', vhdl_text)
    if not m:
        return None

    start = m.end()
    depth = 1
    pos = start
    while pos < len(vhdl_text) and depth > 0:
        if vhdl_text[pos] == '(':
            depth += 1
        elif vhdl_text[pos] == ')':
            depth -= 1
        pos += 1

    inner = vhdl_text[start:pos - 1]

    # Extract all VHDL string literals, handling "" escape
    fragments = []
    in_string = False
    current = []
    i = 0
    while i < len(inner):
        ch = inner[i]
        if not in_string:
            if ch == '"':
                in_string = True
                current = []
        else:
            if ch == '"':
                if i + 1 < len(inner) and inner[i + 1] == '"':
                    current.append('"')
                    i += 2
                    continue
                else:
                    fragments.append(''.join(current))
                    in_string = False
            else:
                current.append(ch)
        i += 1

    return ''.join(fragments)


def parse_payload(payload):
    """Parse metadata||spice_text payload.

    Returns:
        dialect: simulator dialect ('xyce', 'ngspice', etc.)
        name:    subcircuit name
        ports:   list of (spice_name, vhdl_name, direction) tuples
        params:  list of (spice_name, vhdl_name) tuples
        spice:   reconstructed SPICE text (newlines restored)
    """
    sep = payload.find('||')
    if sep < 0:
        spice = payload.replace('~NL~', '\n')
        return 'xyce', None, [], [], spice

    meta_str = payload[:sep]
    spice_flat = payload[sep + 2:]
    spice = spice_flat.replace('~NL~', '\n')

    dialect = 'xyce'
    name = None
    ports = []
    params = []

    for field in meta_str.split('|'):
        if field.startswith('DIALECT:'):
            dialect = field[8:]
        elif field.startswith('SUBCKT:'):
            name = field[7:]
        elif field.startswith('PORT:'):
            parts = field[5:].split(':')
            if len(parts) >= 3:
                ports.append((parts[0], parts[1], parts[2]))
            elif len(parts) >= 2:
                ports.append((parts[0], parts[1], 'inout'))
        elif field.startswith('PARAM:'):
            parts = field[6:].split(':')
            if len(parts) >= 2:
                params.append((parts[0], parts[1]))

    return dialect, name, ports, params, spice


def generate_cosim_deck(name, ports, params, spice, vdd=1.8, tstop='100ns',
                        bridge_lib='libcosim_bridge.so'):
    """Generate a complete Xyce netlist with DPWL hooks at boundary ports.

    For each 'in' port:  add a DPWL source with URI callback to the cosim bridge
    For each 'out' port: node voltage read via obtainResponse by the cosim driver
    Power ports get DC voltage sources.
    """
    lines = []
    lines.append(f'* Xyce cosim deck for {name}')
    lines.append(f'* Auto-generated by xyce_from_vhdl.py')
    lines.append('')

    # Include the original subcircuit definition
    lines.append('* --- Original subcircuit ---')
    lines.append(spice.rstrip())
    lines.append('')

    # Instantiate the subcircuit
    lines.append('* --- Top-level instance with PWL hooks ---')
    inst_ports = []
    for spice_name, vhdl_name, direction in ports:
        inst_ports.append(f'n_{spice_name.lower()}')
    lines.append(f'X1 {" ".join(inst_ports)} {name}')
    lines.append('')

    for spice_name, vhdl_name, direction in ports:
        node = f'n_{spice_name.lower()}'

        if direction == 'in':
            # DPWL voltage source: Xyce calls back into bridge for NVC values
            lines.append(f'* D2A: NVC .{vhdl_name} -> {node}')
            lines.append(f'V_{vhdl_name} {node} 0 PWL FILE'
                         f' "code:{bridge_lib}:nvc_bridge_init:d2a:{vhdl_name}"')
            lines.append('')

        elif direction == 'out':
            # DPWL current source (zero current): reads node voltage,
            # pushes to bridge for NVC to pick up
            lines.append(f'* A2D: {node} -> NVC .{vhdl_name}')
            lines.append(f'I_{vhdl_name} {node} 0 PWL FILE'
                         f' "code:{bridge_lib}:nvc_bridge_init:a2d:{vhdl_name}"')
            lines.append('')

        elif direction == 'power':
            upper = spice_name.upper()
            voltage = 0.0 if upper in ('VSS', 'GND') else vdd
            lines.append(f'* Power: {spice_name} = {voltage}V')
            lines.append(f'V_{spice_name.lower()} {node} 0 {voltage}')
            lines.append('')

        else:
            # inout — D2A voltage source + A2D current source
            lines.append(f'* Bidirectional: NVC .{vhdl_name} <-> {node}')
            lines.append(f'V_{vhdl_name} {node} 0 PWL FILE'
                         f' "code:{bridge_lib}:nvc_bridge_init:d2a:{vhdl_name}"')
            lines.append(f'I_{vhdl_name}_mon {node} 0 PWL FILE'
                         f' "code:{bridge_lib}:nvc_bridge_init:a2d:{vhdl_name}"')
            lines.append('')

    # Analysis
    lines.append(f'.tran 0 {tstop}')
    lines.append('')

    # Print all boundary nodes
    print_nodes = ' '.join(f'V(n_{p[0].lower()})' for p in ports if p[2] != 'power')
    if print_nodes:
        lines.append(f'.print tran {print_nodes}')
    lines.append('')
    lines.append('.end')
    lines.append('')

    return '\n'.join(lines)


def generate_boundary_config(name, ports):
    """Generate boundary config mapping VHDL signals to cosim bridge / Xyce nodes."""
    lines = []
    lines.append(f'# Boundary config for {name}')
    lines.append(f'# Auto-generated by xyce_from_vhdl.py')
    lines.append('#')
    lines.append('# Format: D2A <nvc_signal_path> <bridge_signal_name>')
    lines.append('#         A2D <nvc_signal_path> <xyce_response_var>')
    lines.append('')

    for spice_name, vhdl_name, direction in ports:
        node = f'n_{spice_name.lower()}'

        if direction == 'in':
            lines.append(f'D2A .{vhdl_name} {vhdl_name}')

        elif direction == 'out':
            lines.append(f'A2D .{vhdl_name} {vhdl_name}')

        elif direction == 'power':
            lines.append(f'# power: {spice_name} (no boundary)')

        else:
            # inout
            lines.append(f'D2A .{vhdl_name} {vhdl_name}')
            lines.append(f'A2D .{vhdl_name} {vhdl_name}')

    lines.append('')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Extract Xyce subcircuit from VHDL wrapper and generate cosim deck')
    parser.add_argument('vhdl', nargs='+',
                        help='VHDL wrapper file(s) from xyce_to_vhdl.py')
    parser.add_argument('-o', '--outdir', default='.',
                        help='Output directory (default: .)')
    parser.add_argument('--vdd', type=float, default=1.8,
                        help='Supply voltage for power ports (default: 1.8)')
    parser.add_argument('--tstop', default='100ns',
                        help='Simulation stop time (default: 100ns)')
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)

    for vhdl_path in args.vhdl:
        with open(vhdl_path, 'r') as f:
            vhdl_text = f.read()

        payload = extract_spice_subckt_payload(vhdl_text)
        if payload is None:
            print(f'{vhdl_path}: no spice_subckt() found, skipping',
                  file=sys.stderr)
            continue

        dialect, name, ports, params, spice = parse_payload(payload)
        print(f'{vhdl_path}: dialect={dialect}', file=sys.stderr)
        if name is None:
            name = os.path.splitext(os.path.basename(vhdl_path))[0]

        # Generate complete cosim deck
        deck = generate_cosim_deck(name, ports, params, spice,
                                   vdd=args.vdd, tstop=args.tstop)
        cir_path = os.path.join(args.outdir, f'{name}.cir')
        with open(cir_path, 'w') as f:
            f.write(deck)
        print(f'{cir_path}: cosim deck ({len(deck.splitlines())} lines)')

        # Generate boundary config
        boundary = generate_boundary_config(name, ports)
        bnd_path = os.path.join(args.outdir, f'{name}.boundary')
        with open(bnd_path, 'w') as f:
            f.write(boundary)
        print(f'{bnd_path}: boundary config')


if __name__ == '__main__':
    main()
